const { test } = require('@playwright/test');
const { MainPage } = require('./tests/pageObjects/main.page')



  test.describe.configure({
    mode: "parallel"
  })

  test('Should check deactivation of an active unit.', async ({ page }) => {
    const mainPage = new MainPage(page);
    page.setViewportSize({ width: 1700, height: 1080 });
    await mainPage.openLetkaBackend()
    await mainPage.clickVhidBtn()
    await mainPage.FillEmailField()
    await mainPage.FillPasswordField()
    await mainPage.clickUviytiBtn()
    await mainPage.clickProfileDropdown()
    await mainPage.SelectOholoshenyaBtn()
    await mainPage.ClickMojiOholoshenya()
    await mainPage.clickPodatiOholoshBtn()
    await mainPage.clickCategoryDropdown()
    await mainPage.clickBudTehnikaDropdown()
    await mainPage.clickAvtoKranyDropdown()
    await mainPage.clickAvtoKranyBtn()
    await mainPage.fillNazvaField()
    await mainPage.fillVyrobnikField()
    await mainPage.clickWagnerBtn()
    await mainPage.fillNazvaModeliField()
    await mainPage.fillTehHarakteristikiField()
    await mainPage.fieldDetalyiOpysField()
    await mainPage.clickVybratyNaMapiBtn()
    await mainPage.clickPidtverdityVyborBtn()
    await mainPage.clickDaliBtn()
    await page.waitForTimeout(1000)
    await mainPage.InputImage1()
    await page.waitForTimeout(1000)
    await mainPage.ClickDaliBtn2()
    await mainPage.FillPoslugiField()
    await mainPage.ClickUborkaBtn()
    await mainPage.ClickDaliBtn3()
    await mainPage.FillMinZamovlenyaField()
    await mainPage.ClickDaliBtn4()
    await mainPage.ClickPodatyNarozglyadBtn()
    await mainPage.clickProfileDropdown()
    await mainPage.ClickVyityBtn()
    await mainPage.clickVhidBtn()
    await mainPage.FillAdminEmailFild()
    await mainPage.FillAdminPasswordField()
    await mainPage.clickUviytiBtn()
    await mainPage.ClickAdminGearsBtn()
    await mainPage.ClickOholoshenyaBtn()
    await mainPage.FillZnaytyInput()
    await page.waitForTimeout(1000)
    await mainPage.clickDiyaBtn()
    await mainPage.ClickApproveBtn()
    await page.waitForTimeout(1000)
    await mainPage.ClickHomeBtn()
    await page.waitForTimeout(1000)
    await mainPage.clickProfileDropdown()
    await mainPage.ClickVyityBtn()
    await mainPage.clickVhidBtn()
    await mainPage.FillEmailField()
    await mainPage.FillPasswordField()
    await mainPage.clickUviytiBtn()
    await mainPage.clickProfileDropdown()
    await mainPage.SelectOholoshenyaBtn()
    await mainPage.ClickMojiOholoshenya()
    await mainPage.ClickDeaktyvatyBtn()
    await mainPage.CheckDeaktyvatyBtn()
    await mainPage.ClickCloseBtn()
    await mainPage.ClickDeaktyvatyBtn()
    await mainPage.ClickTakBtn()
    await mainPage.CheckNenayeOholoshenText()
    await mainPage.ClickDeaktuvovaniBtn()
    await mainPage.CheckOholoshenyaText()
    await mainPage.clickProfileDropdown()
    await mainPage.ClickVyityBtn()
    await mainPage.clickVhidBtn()
    await mainPage.FillAdminEmailFild()
    await mainPage.FillAdminPasswordField()
    await mainPage.clickUviytiBtn()
    await mainPage.ClickAdminGearsBtn()
    await mainPage.ClickOholoshenyaBtn()
    await mainPage.ClickDeaktuvovaniBtn()
    await mainPage.FillZnaytyInput()
    await page.waitForTimeout(1000)
    await mainPage.ClickBucketBtn()
    await page.waitForTimeout(1000)
    await mainPage.ClickTakBtn()
  })